import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { VehiclesProvider } from '@/contexts/VehiclesContext';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from '../contexts/CartContext';

const roboto = Roboto({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <ThemeProvider theme={theme}>
          <VehiclesProvider>
            <CartProvider>
              <Navbar/>
              <main style={{ flex: 1 }}>{children}</main>
              <Footer />
            </CartProvider>
          </VehiclesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
